### PR TITLE
Updating Docker image dependency to starburstdata/presto:338-e.7

### PR DESCRIPTION
**Pull request by jeff303**
Updating paths to config and JVM options files

Setting execute perms on start and test scripts

### CODE REVIEW

**Comment by jeff303** [comment]
These changes seem to get everything building and running again.  However, the server is still apparently not processing queries.  This is the output when running `test.sh`:

```
{"id":"20210517_194311_00002_uffcq","infoUri":"https://krb5-presto-example-com:7778/ui/query.html?20210517_194311_00002_uffcq","nextUri":"https://krb5-presto-example-com:7778/v1/statement/queued/20210517_194311_00002_uffcq/y378aae8916391b0f2518c82296412dbb5dd86e85/1","stats":{"state":"QUEUED","queued":true,"scheduled":false,"nodes":0,"totalSplits":0,"queuedSplits":0,"runningSplits":0,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":0,"elapsedTimeMillis":0,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"spilledBytes":0},"warnings":[]}
```

Unsure why this stays in `QUEUED` state.  I checked the log files for Presto (not knowing hardly anything about that system) and don't see anything obvious.

**Comment by mik-laj** [comment]
This is expected behavior. You have to poll the status to get the results.

**Comment by mik-laj** [comment]
I'll be adding the code that does this in a moment.

**Comment by mik-laj** [comment]
@jeff303 Thanks. Merged!

**Comment by jeff303** [comment]
> @jeff303 Thanks. Merged!

Thanks for the super fast work on this!  I'm trying the update now, and getting

```
./send-presto-query.sh: line 30:
  kinit -kt /root/share/kerberos.keytab bob@EXAMPLE.COM &>/dev/null;
  curl -X POST     --insecure     --negotiate     -u :     'https://krb5-presto-example-com:7778/v1/statement'     --data ${SQL@Q}
  : bad substitution
```

I tried just changing that to `${SQL}` and it makes it past that, but the new error in the response is:

```
lookup 1: no such host
parse error: Invalid numeric literal at line 2, column 7
```

I also notice that if I change `1` to some other number in the `SELECT` statement then that shows up instead.  Is that a valid query in Presto?

**Comment by mik-laj** [comment]
@jeff303 You have an outdated bash version. If you want to run this you should replace `${SQL@Q}` with `"${SQL}"`, but if some special characters appear then this script will not work properly.
See: https://unix.stackexchange.com/questions/379181/escape-a-variable-for-use-as-content-of-another-script

**Pull request merged**
